export interface CameraFilter {
  id: string;
  name: string;
  label: string;
  cssFilter: string;
  description: string;
  icon?: string;
  category?: 'beauty' | 'tone' | 'creative';
  previewBadgeBg?: string;
}

export const CAMERA_FILTERS: CameraFilter[] = [
  {
    id: 'normal',
    name: 'Normal',
    label: 'Tanpa Filter',
    cssFilter: 'none',
    description: 'Warna alami kamera tanpa efek tambahan.',
    icon: '✨',
    category: 'tone',
    previewBadgeBg: 'from-gray-600 to-gray-800',
  },
  {
    id: 'tiktok_smooth',
    name: 'TikTok Smooth Beauty',
    label: 'Porcelain Skin',
    cssFilter: 'brightness(108%) contrast(97%) saturate(106%)',
    description: 'Kulit halus bercahaya ala filter beauty TikTok populer.',
    icon: '💄',
    category: 'beauty',
    previewBadgeBg: 'from-pink-500 to-rose-500',
  },
  {
    id: 'tiktok_rosy_blush',
    name: 'Rosy Cheek Blush',
    label: 'TikTok Blush Glow',
    cssFilter: 'saturate(125%) hue-rotate(-6deg) brightness(107%) contrast(102%)',
    description: 'Sentuhan rona pipi segar dan bibir merona glowing alami.',
    icon: '🌸',
    category: 'beauty',
    previewBadgeBg: 'from-rose-400 to-pink-600',
  },
  {
    id: 'tiktok_golden_hour',
    name: 'Golden Hour Sunkissed',
    label: 'Sunkissed Glow',
    cssFilter: 'sepia(24%) contrast(108%) brightness(105%) saturate(122%) hue-rotate(-4deg)',
    description: 'Pancaran hangat matahari sore estetik yang mempertegas garis wajah.',
    icon: '✨',
    category: 'beauty',
    previewBadgeBg: 'from-amber-400 to-orange-500',
  },
  {
    id: 'tiktok_korean_doll',
    name: 'Korean Doll High-Key',
    label: 'K-Pop Idol Glow',
    cssFilter: 'brightness(116%) contrast(94%) saturate(110%)',
    description: 'Pencahayaan terang lembut khas foto studio idol Korea.',
    icon: '🎀',
    category: 'beauty',
    previewBadgeBg: 'from-purple-400 to-pink-400',
  },
  {
    id: 'tiktok_clean_girl',
    name: 'Clean Girl Aesthetic',
    label: 'Fresh Natural',
    cssFilter: 'contrast(105%) brightness(105%) saturate(108%)',
    description: 'Penampilan segar, bersih natural tanpa terasa diedit.',
    icon: '🌿',
    category: 'beauty',
    previewBadgeBg: 'from-emerald-400 to-teal-500',
  },
  {
    id: 'tiktok_glass_skin',
    name: 'Glass Skin Dewy',
    label: 'K-Beauty Dew',
    cssFilter: 'brightness(114%) contrast(104%) saturate(112%)',
    description: 'Tampilan kulit kaca berkilau bening khas tren K-Beauty.',
    icon: '💎',
    category: 'beauty',
    previewBadgeBg: 'from-sky-400 to-indigo-500',
  },
  {
    id: 'tiktok_porcelain_doll',
    name: 'Porcelain Doll White',
    label: 'Porcelain Skin',
    cssFilter: 'brightness(116%) contrast(96%) saturate(108%) sepia(8%) hue-rotate(-5deg)',
    description: 'Kulit porselen bening bercahaya dengan highlight lembut khas boneka.',
    icon: '🎀',
    category: 'beauty',
    previewBadgeBg: 'from-rose-300 to-pink-500',
  },
  {
    id: 'tiktok_cherry_tint',
    name: 'Cherry Syrup Tint',
    label: 'Cherry Gloss',
    cssFilter: 'saturate(136%) contrast(106%) brightness(108%) hue-rotate(-8deg)',
    description: 'Rona bibir dan pipi sirup cherry merah merona manis nan segar.',
    icon: '🍒',
    category: 'beauty',
    previewBadgeBg: 'from-red-500 to-rose-600',
  },
  {
    id: 'tiktok_glazed_donut',
    name: 'Glazed Donut Glow',
    label: 'Hailey Dew',
    cssFilter: 'brightness(112%) contrast(102%) saturate(114%) sepia(10%)',
    description: 'Tampilan super dewy dan berkilau alami ala Hailey Bieber.',
    icon: '✨',
    category: 'beauty',
    previewBadgeBg: 'from-amber-300 to-pink-400',
  },
  {
    id: 'tiktok_douyin_fair',
    name: 'Douyin Fair High-Key',
    label: 'Douyin Doll',
    cssFilter: 'brightness(120%) contrast(92%) saturate(105%)',
    description: 'Tone putih cerah mulus dengan nuansa lembut ala makeup viral Douyin.',
    icon: '👑',
    category: 'beauty',
    previewBadgeBg: 'from-fuchsia-400 to-pink-500',
  },
  {
    id: 'tiktok_peach_fuzz',
    name: 'Peach Fuzz Velvet',
    label: 'Peach Glow',
    cssFilter: 'brightness(108%) contrast(98%) saturate(118%) sepia(12%) hue-rotate(-8deg)',
    description: 'Rona buah persik lembut yang manis memikat.',
    icon: '🍑',
    category: 'beauty',
    previewBadgeBg: 'from-orange-400 to-pink-500',
  },
  {
    id: 'tiktok_matcha_fair',
    name: 'Matcha Tone-Up Fair',
    label: 'Tone-Up Cold',
    cssFilter: 'contrast(103%) brightness(110%) saturate(98%) hue-rotate(10deg)',
    description: 'Koreksi kemerahan kulit dengan tone dingin sejuk yang mencerahkan.',
    icon: '🍵',
    category: 'beauty',
    previewBadgeBg: 'from-emerald-300 to-teal-400',
  },
  {
    id: 'tiktok_espresso_glam',
    name: 'Espresso Cozy Glam',
    label: 'Latte Makeup',
    cssFilter: 'sepia(30%) contrast(114%) brightness(102%) saturate(118%) hue-rotate(-12deg)',
    description: 'Nuansa hangat cokelat latte dengan kontras lembut elegan.',
    icon: '☕',
    category: 'beauty',
    previewBadgeBg: 'from-amber-700 to-amber-900',
  },
  {
    id: 'tiktok_cloud_dream',
    name: 'Cloud Nine Dreamy',
    label: 'Ethereal Cloud',
    cssFilter: 'brightness(118%) contrast(90%) saturate(110%)',
    description: 'Efek dreamy lembut berkabut putih seperti berdiri di atas awan.',
    icon: '☁️',
    category: 'beauty',
    previewBadgeBg: 'from-indigo-300 to-purple-400',
  },
  {
    id: 'tiktok_baddie_contour',
    name: 'Baddie Golden Glow',
    label: 'Golden Contour',
    cssFilter: 'contrast(116%) brightness(106%) saturate(125%) sepia(15%)',
    description: 'Kontras tegas dengan highlight keemasan yang menonjolkan fitur wajah.',
    icon: '💄',
    category: 'beauty',
    previewBadgeBg: 'from-yellow-500 to-amber-600',
  },
  {
    id: 'bw',
    name: 'B&W Monokrom',
    label: 'Classic Monochrome',
    cssFilter: 'grayscale(100%) contrast(120%) brightness(102%)',
    description: 'Klasik hitam-putih kontras tajam ala studio monokrom Korea.',
    icon: '🖤',
    category: 'tone',
    previewBadgeBg: 'from-zinc-900 to-zinc-600',
  },
  {
    id: 'vintage',
    name: 'Film Roll Vintage',
    label: 'Analog 35mm',
    cssFilter: 'sepia(45%) contrast(110%) brightness(98%) saturate(115%) hue-rotate(-10deg)',
    description: 'Tone hangat bernuansa rol film analog 35mm nostalgia.',
    icon: '📜',
    category: 'tone',
    previewBadgeBg: 'from-amber-800 to-amber-600',
  },
  {
    id: 'vhs_90s',
    name: '90s Camcorder',
    label: 'Retro VHS',
    cssFilter: 'contrast(125%) saturate(145%) brightness(104%) sepia(20%) hue-rotate(10deg)',
    description: 'Estetika video camcorder era 90-an dengan saturasi berani.',
    icon: '📼',
    category: 'tone',
    previewBadgeBg: 'from-fuchsia-800 to-purple-600',
  },
  {
    id: 'pastel',
    name: 'Soft Warm Pastel',
    label: 'Korean Pastel Glow',
    cssFilter: 'brightness(112%) contrast(96%) saturate(115%) sepia(15%)',
    description: 'Warna pastel lembut dan hangat, membuat kulit halus glowing.',
    icon: '🌸',
    category: 'tone',
    previewBadgeBg: 'from-pink-500 to-rose-400',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    label: 'Neon Night',
    cssFilter: 'contrast(135%) saturate(160%) hue-rotate(185deg) brightness(98%)',
    description: 'Vibes malam neon futuristik dengan warna elektrik menyala.',
    icon: '⚡',
    category: 'tone',
    previewBadgeBg: 'from-cyan-600 to-blue-700',
  },
  {
    id: 'teal_orange',
    name: 'Teal & Orange',
    label: 'Cinematic Grade',
    cssFilter: 'contrast(118%) saturate(130%) sepia(25%) hue-rotate(-18deg) brightness(102%)',
    description: 'Color grading sinematik blockbuster Hollywood terpopuler.',
    icon: '🎬',
    category: 'tone',
    previewBadgeBg: 'from-teal-600 to-orange-600',
  },
  {
    id: 'dreamy_glow',
    name: 'Dreamy Soft Glow',
    label: 'Ethereal Bloom',
    cssFilter: 'brightness(116%) contrast(92%) saturate(108%)',
    description: 'Efek soft focus lembut dan dreamy mempesona.',
    icon: '☁️',
    category: 'tone',
    previewBadgeBg: 'from-violet-400 to-pink-300',
  },
];

export const DEFAULT_FILTER = CAMERA_FILTERS[0];
